name: tech_talk_django_pg_triggers

volumes:
  postgres_data: {}
  rabbitmq_data: {}
  redis_data: {}

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    shm_size: 512m
    environment:
      __ENV__: 'Local'
      # Django
      # ======================================================================
      DOMAIN: '0.0.0.0:8000'
      SSL: 'off'
      MEDIA_URL: '/media/'
      STATIC_URL: '/static/'
      REDIS_NETLOC: 'redis://redis:6379/0'
      RABBIT_NETLOC: 'amqp://rabbitmq:5672'
      POSTGRES_NETLOC: 'postgresql://local:local@postgres:5432/local'
      SECRET_KEY: 'django-insecure-yb94mPikxv8DF9XFcz9ipV2tGi7cpZPk'
      DJANGO_SUPERUSER_USERNAME: 'admin'
      DJANGO_SUPERUSER_PASSWORD: 'admin'
      DJANGO_SUPERUSER_EMAIL: 'admin@example.com'
    ports:
      - '8000:8000'
    healthcheck:
      test: [ "CMD", "echo", "App health check passed" ]
      interval: 60s
      timeout: 3s
      retries: 1
      start_period: 10s
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:16.2
    shm_size: 512m
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U local" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3.13
    hostname: default_rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7.2
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
